// placeholder data
export const users = [
    {
        id: 1,
        firstName: 'Alice',
        lastName: 'Smith',
        email: 'alice.smith@example.com',
        deliveryPlace: 'New York',
        paymentType: 'card',
        discountType: 'premium',
        isActive: true,
    },
    {
        id: 2,
        firstName: 'Bob',
        lastName: 'Johnson',
        email: 'bob.johnson@example.com',
        deliveryPlace: 'Los Angeles',
        paymentType: 'cash',
        discountType: 'none',
        isActive: false,
    },
    {
        id: 3,
        firstName: 'Emily',
        lastName: 'Brown',
        email: 'emily.brown@example.com',
        deliveryPlace: 'London',
        paymentType: 'card',
        discountType: 'basic',
        isActive: true,
    },
    {
        id: 4,
        firstName: 'David',
        lastName: 'Jones',
        email: 'david.jones@example.com',
        deliveryPlace: 'Sydney',
        paymentType: 'cash',
        discountType: 'premium',
        isActive: false,
    },
    {
        id: 5,
        firstName: 'Sophia',
        lastName: 'Davis',
        email: 'sophia.davis@example.com',
        deliveryPlace: 'Paris',
        paymentType: 'card',
        discountType: 'none',
        isActive: true,
    },
    {
        id: 6,
        firstName: 'Michael',
        lastName: 'Wilson',
        email: 'michael.wilson@example.com',
        deliveryPlace: 'Tokyo',
        paymentType: 'cash',
        discountType: 'basic',
        isActive: true,
    },
    {
        id: 7,
        firstName: 'Emma',
        lastName: 'Martinez',
        email: 'emma.martinez@example.com',
        deliveryPlace: 'Madrid',
        paymentType: 'card',
        discountType: 'premium',
        isActive: false,
    },
    {
        id: 8,
        firstName: 'James',
        lastName: 'Garcia',
        email: 'james.garcia@example.com',
        deliveryPlace: 'Berlin',
        paymentType: 'cash',
        discountType: 'none',
        isActive: true,
    },
    {
        id: 9,
        firstName: 'Olivia',
        lastName: 'Lopez',
        email: 'olivia.lopez@example.com',
        deliveryPlace: 'Rome',
        paymentType: 'card',
        discountType: 'basic',
        isActive: false,
    },
    {
        id: 10,
        firstName: 'Isabella',
        lastName: 'Rodriguez',
        email: 'isabella.rodriguez@example.com',
        deliveryPlace: 'Mexico City',
        paymentType: 'card',
        discountType: 'premium',
        isActive: true,
    },
    {
        id: 11,
        firstName: 'William',
        lastName: 'Gonzalez',
        email: 'william.gonzalez@example.com',
        deliveryPlace: 'Buenos Aires',
        paymentType: 'cash',
        discountType: 'none',
        isActive: false,
    },
    {
        id: 12,
        firstName: 'Mia',
        lastName: 'Hernandez',
        email: 'mia.hernandez@example.com',
        deliveryPlace: 'Sao Paulo',
        paymentType: 'card',
        discountType: 'basic',
        isActive: true,
    },
    {
        id: 13,
        firstName: 'Alexander',
        lastName: 'Perez',
        email: 'alexander.perez@example.com',
        deliveryPlace: 'Lima',
        paymentType: 'cash',
        discountType: 'premium',
        isActive: true,
    },
    {
        id: 14,
        firstName: 'Charlotte',
        lastName: 'Torres',
        email: 'charlotte.torres@example.com',
        deliveryPlace: 'Caracas',
        paymentType: 'card',
        discountType: 'none',
        isActive: true,
    },
    {
        id: 15,
        firstName: 'Ethan',
        lastName: 'Gomez',
        email: 'ethan.gomez@example.com',
        deliveryPlace: 'Brasilia',
        paymentType: 'cash',
        discountType: 'basic',
        isActive: false,
    },
    {
        id: 16,
        firstName: 'Amelia',
        lastName: 'Rivera',
        email: 'amelia.rivera@example.com',
        deliveryPlace: 'Santiago',
        paymentType: 'card',
        discountType: 'premium',
        isActive: true,
    },
    {
        id: 17,
        firstName: 'Liam',
        lastName: 'Diaz',
        email: 'liam.diaz@example.com',
        deliveryPlace: 'Montevideo',
        paymentType: 'cash',
        discountType: 'none',
        isActive: false,
    },
    {
        id: 18,
        firstName: 'Ava',
        lastName: 'Alvarez',
        email: 'ava.alvarez@example.com',
        deliveryPlace: 'Lisbon',
        paymentType: 'card',
        discountType: 'basic',
        isActive: true,
    },
    {
        id: 19,
        firstName: 'Lucas',
        lastName: 'Moreno',
        email: 'lucas.moreno@example.com',
        deliveryPlace: 'Bogota',
        paymentType: 'cash',
        discountType: 'premium',
        isActive: true,
    },
    {
        id: 20,
        firstName: 'Harper',
        lastName: 'Ruiz',
        email: 'harper.ruiz@example.com',
        deliveryPlace: 'Quito',
        paymentType: 'card',
        discountType: 'none',
        isActive: true,
    },
];
